### ISSUE TITLE
Press "Sign and Send" takes forever...

### ISSUE THREAD

**Issue by oscarluizsn** [LeoIannacone/goopg#14]
Hello!

I install googp as described in your page, but can't send signed messages. I click on "Sign and Send" and nothing occours.

Can you help me?

Regards,

**Comment by LeoIannacone** [comment]
Look at ``` ~/.cache/goopg/log``` 

You may find some useful info there ... Let me know.

**Comment by LeoIannacone** [comment]
Please,

consider to re-open if you need more help.

**Comment by oscarluizsn** [comment]
Sorry by the delay. The log content is:

2015-03-26 16:26:30,814:ERROR:STDERR:Traceback (most recent call last):
2015-03-26 16:26:30,814:ERROR:STDERR:  File "/usr/share/goopg/chrome-main.py", line 71, in <module>
2015-03-26 16:26:30,814:ERROR:STDERR:main()
2015-03-26 16:26:30,814:ERROR:STDERR:  File "/usr/share/goopg/chrome-main.py", line 62, in main
2015-03-26 16:26:30,814:ERROR:STDERR:parse_and_send_result(bundle)
2015-03-26 16:26:30,814:ERROR:STDERR:  File "/usr/share/goopg/chrome-main.py", line 57, in parse_and_send_result
2015-03-26 16:26:30,815:ERROR:STDERR:result = handler.parse(b)
2015-03-26 16:26:30,815:ERROR:STDERR:  File "/usr/share/goopg/commandhandler.py", line 26, in parse
2015-03-26 16:26:30,815:ERROR:STDERR:result = self.init(bundle)
2015-03-26 16:26:30,815:ERROR:STDERR:  File "/usr/share/goopg/commandhandler.py", line 40, in init
2015-03-26 16:26:30,815:ERROR:STDERR:if not 'options' in bundle and not 'username' in bundle['options']:
2015-03-26 16:26:30,815:ERROR:STDERR:KeyError
2015-03-26 16:26:30,815:ERROR:STDERR::
2015-03-26 16:26:30,815:ERROR:STDERR:'options'
2015-03-26 16:27:21,850:ERROR:STDERR:Traceback (most recent call last):
2015-03-26 16:27:21,850:ERROR:STDERR:  File "/usr/share/goopg/chrome-main.py", line 71, in <module>
2015-03-26 16:27:21,850:ERROR:STDERR:main()
2015-03-26 16:27:21,850:ERROR:STDERR:  File "/usr/share/goopg/chrome-main.py", line 62, in main
2015-03-26 16:27:21,850:ERROR:STDERR:parse_and_send_result(bundle)
2015-03-26 16:27:21,850:ERROR:STDERR:  File "/usr/share/goopg/chrome-main.py", line 57, in parse_and_send_result
2015-03-26 16:27:21,850:ERROR:STDERR:result = handler.parse(b)
2015-03-26 16:27:21,850:ERROR:STDERR:  File "/usr/share/goopg/commandhandler.py", line 26, in parse
2015-03-26 16:27:21,850:ERROR:STDERR:result = self.init(bundle)
2015-03-26 16:27:21,851:ERROR:STDERR:  File "/usr/share/goopg/commandhandler.py", line 40, in init
2015-03-26 16:27:21,851:ERROR:STDERR:if not 'options' in bundle and not 'username' in bundle['options']:
2015-03-26 16:27:21,851:ERROR:STDERR:KeyError
2015-03-26 16:27:21,851:ERROR:STDERR::
2015-03-26 16:27:21,851:ERROR:STDERR:'options

**Comment by LeoIannacone** [comment]
It seems extension can't find the USERNAME.

I just pushed  a new version of Goopg in the PPA. Please consider an update of you sistem.

Let me know if this fixes your issue.

**Comment by oscarluizsn** [comment]
Sounds that is working now.

Thanks for your assistance.

-----
Oscar Luiz da Silva Neto
Director, Service Infrastructure Practices
KnowHow IT Services
Mobile: +55-51-80570056
Skype: oscarluizsn
PGP Key ID: F69244B3 
<http://keyserver.pgp.com/vkd/DownloadKey.event?keyid=0xD9D85092F69244B3>
http://www.knowhow.eti.br

*"Eu apóio o PLC 3722/2012".*


 
2015-03-27 7:06 GMT-03:00 Leo Iannacone <notifications@github.com>:

**Comment by oscarluizsn** [comment]
But... if the contact is already register, didn't work:

SMTPRecipientsRefused: {'"Becker': (553, "5.1.2 We weren't able to find the 
recipient domain. Please check for any\n5.1.2 spelling errors, and make 
sure you didn't enter any spaces, periods,\n5.1.2 or other punctuation 
after the recipient's email address. 10sm4734178qha.38 - gsmtp"), 
'Fabricio" <fabricio.becker@hp.com>': (553, "5.1.2 We weren't able to find 
the recipient domain. Please check for any\n5.1.2 spelling errors, and make 
sure you didn't enter any spaces, periods,\n5.1.2 or other punctuation 
after the recipient's email address. 10sm4734178qha.38 - gsmtp")}
2015-03-28 22:11:43,185:ERROR:CommandHandler:{'"Becker': (553, "5.1.2 We 
weren't able to find the recipient domain. Please check for any\n5.1.2 
spelling errors, and make sure you didn't enter any spaces, periods,\n5.1.2 
or other punctuation after the recipient's email address. 10sm4734178qha.38 
- gsmtp"), 'Fabricio" <fabricio.becker@hp.com>': (553, "5.1.2 We weren't 
able to find the recipient domain. Please check for any\n5.1.2 spelling 
errors, and make sure you didn't enter any spaces, periods,\n5.1.2 or other 
punctuation after the recipient's email address. 10sm4734178qha.38 - 
gsmtp")}
Traceback (most recent call last):
  File "/usr/share/goopg/commandhandler.py", line 89, in sign
    self.gmail.send(id, new_message)
  File "/usr/share/goopg/gmail/__init__.py", line 262, in send
    self.smtp.sendmail(self.username, receivers, msg_str)
  File "/usr/lib/python2.7/smtplib.py", line 735, in sendmail
    raise SMTPRecipientsRefused(senderrs)
SMTPRecipientsRefused: {'"Becker': (553, "5.1.2 We weren't able to find the 
recipient domain. Please check for any\n5.1.2 spelling errors, and make 
sure you didn't enter any spaces, periods,\n5.1.2 or other punctuation 
after the recipient's email address. 10sm4734178qha.38 - gsmtp"), 
'Fabricio" <fabricio.becker@hp.com>': (553, "5.1.2 We weren't able to find 
the recipient domain. Please check for any\n5.1.2 spelling errors, and make 
sure you didn't enter any spaces, periods,\n5.1.2 or other punctuation 
after the recipient's email address. 10sm4734178qha.38 - gsmtp")}


If I delete the contact and put directly the email, works. The error is 
consistent.

-----
Oscar Luiz da Silva Neto
Director, Service Infrastructure Practices
KnowHow IT Services
Mobile: +55-51-80570056
Skype: oscarluizsn
PGP Key ID: F69244B3 
<http://keyserver.pgp.com/vkd/DownloadKey.event?keyid=0xD9D85092F69244B3>
http://www.knowhow.eti.br

*"Eu apóio o PLC 3722/2012".*


 
2015-03-28 21:39 GMT-03:00 Oscar Luiz da Silva Neto <oscar@knowhow.eti.br>:

**Comment by LeoIannacone** [comment]
It looks like your contact is:
```
Fabricio" <fabricio.becker@hp.com>
```
and Python.email says that's not in the correct form.

Can you please confirm this ? Or your contact has another signature?.. something like:

"Becker, Fabricio <fabricio......>" 

Let me know ...

**Comment by LeoIannacone** [comment]
I thinks this issue is fixed.

Please confirm after updating your system at version 0.2.2 of the plugin..

Cheers

**Comment by oscarluizsn** [comment]
I didn't find the 0.2.2 in the repository.

**Comment by oscarluizsn** [comment]
Found it!

And is working. Thanks for your assistance.

**Comment by LeoIannacone** [comment]
You welcome!.. 

Please, consider to spread the world about Goopg :)

**Comment by gornostal** [comment]
Hi there!

I have a similar issue. It gets stuck at "Sending". I'm using Google Chrome 42.0.2311.90
And there is no `~/.cache/goopg/log`

Please advise.

**Comment by LeoIannacone** [comment]
Hi Aleksandr!

Please, be sure to have installed `goopg-chrome` package and **NOT** the chromium's one.

**Comment by gornostal** [comment]
This is what I'm seeing in the terminal:
`goopg-chrome is already the newest version.`

**Comment by gornostal** [comment]
Maybe this will be helpful
![selection_016](https://cloud.githubusercontent.com/assets/1202543/7220269/da811a48-e6c9-11e4-9b7f-7158d8997230.png)

**Comment by LeoIannacone** [comment]
Yes it is. 

It seems the plugin exists on your machine (and chrome finds it) but it crashes on start.

I tried a fresh installation of google-chrome browser, but I was not able to reproduce the issue with Ubuntu Vivid 15.04.

**Comment by gornostal** [comment]
What is a native host?
Isn't it your python script?

**Comment by gornostal** [comment]
How do I verify it is running?

**Comment by LeoIannacone** [comment]
> What is a native host?
> Isn't it your python script?
Yes, It is.

> How do I verify it is running?
`ps aux | grep goopg` could help ... but the error is clear:
```
Failed to connect: Native host has excited.
```
Which means: the native hosts crashes at some point.


Does the email verification work fine?

**Comment by gornostal** [comment]
> ps aux | grep goopg

Process not found

> Does the email verification work fine?

Don't know. Could you send me something signed? sanya.gornostal@gmail.com

**Comment by LeoIannacone** [comment]
Done.

**Comment by gornostal** [comment]
![selection_018](https://cloud.githubusercontent.com/assets/1202543/7220325/be65523c-e6cb-11e4-93fa-8e00f472d2f5.png)

**Comment by LeoIannacone** [comment]
Did you give proper permission to goopg to access your Google Account ?

**Comment by gornostal** [comment]
I agreed to whatever permissions it needed. I'll try to reinstall it.

**Comment by LeoIannacone** [comment]
Please provide the output of:
`dpkg -l | grep goopg `

**Comment by gornostal** [comment]
```
ii  goopg-chrome                                          0.2.2~trusty                                        all          GPG for Gmail - Chrome browser plugin
ii  goopg-common                                          0.2.2~trusty                                        all          GPG for Gmail - common files
```

**Comment by gornostal** [comment]
If I install Chromium and `goopg-chromium`, should goopg work for both Chrome and Chromium?

**Comment by LeoIannacone** [comment]
The pacakge `goopg-chromium` contains all the files needed to exec goopg in Chromium. It does not contains any file related the Chrome.

**Comment by gornostal** [comment]
Well... it doesn't work for Chromium either.

**Comment by LeoIannacone** [comment]
In file `/usr/share/goopg/logger.py` try to set `level=logging.DEBUG` at line 34

**Comment by gornostal** [comment]
Changed. `~/.cache/goopg/log` still doesn't exist.
Should I reboot or log out?

**Comment by LeoIannacone** [comment]
No.. reboot/logout is not needed.

I think something is wrong in Ubuntu Trusty.

You have to figure out where (and why) it fails.. please, try (if you know Python) to edit /usr/share/goopg/chrome-main.py adding some debug info. You must to write to external files (i.e. /tmp/goopg-tmpdbg), since you lose the std-output.

**Comment by gornostal** [comment]
I think I know Python :)
I'll try to debug.

Could tell how your Chrome plugin connects to python script? In a nutshell.
And how python script is started?

**Comment by LeoIannacone** [comment]
You can find all the info in this file: https://github.com/LeoIannacone/goopg/blob/master/doc/project.md

And here to understand how a py script is executed in chrome browser: https://developer.chrome.com/extensions/messaging

**Comment by gornostal** [comment]
Thanks.
