### ISSUE TITLE
Unable to reach PPA source

### ISSUE THREAD

**Issue by i2000s** [LeoIannacone/goopg#18]
HI there,

Is the launchpad server down or the ppa source has been moved? I found the following error when I use ```sudo apt-get update``` on my Ubuntu 12.04 machine:

```
Fetched 5,627 kB in 12s (464 kB/s)                                             
W: Failed to fetch http://ppa.launchpad.net/team-goopg/goopg/ubuntu/dists/precise/main/source/Sources  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/team-goopg/goopg/ubuntu/dists/precise/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/team-goopg/goopg/ubuntu/dists/precise/main/binary-i386/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
```

I have followed the [instruction](http://leoiannacone.github.io/goopg/) to install the package. The error has occurred for a few weeks I think.

Thanks,
Qi

**Comment by i2000s** [comment]
PS: After looking into this problem, I think the problem is the package for Ubuntu 12.04 is not built (see [the archieve](https://launchpad.net/~team-goopg/+archive/ubuntu/goopg)). Could you rebuilt one package for Ubuntu 12.04 as well? I guess a lot of people is still using the long-supporting version of Ubuntu. Thanks.

**Comment by LeoIannacone** [comment]
Package uploaded to Precise. Thanks for reporting.

**Comment by LeoIannacone** [comment]
Precise won't be supported due to the missing of dh-python in Ubuntu 12.04.

You could try the 14.04 packages.
