### ISSUE TITLE
goopg can't sign and send any email

### ISSUE THREAD

**Issue by warp10** [LeoIannacone/goopg#19]
Altough goopg works great with checking signature and even downloading public keys, trying to sign and send an email, I get the message "Your message was not sent. Please retry.

I get this error message in the log:
2015-09-14 11:43:21,522:ERROR:CommandHandler:Invalid signature hash_algo None
Traceback (most recent call last):
 File "/usr/share/goopg/commandhandler.py", line 87, in sign
   new_message = self.gpgmail.sign(draft)
 File "/usr/share/goopg/gpgmail.py", line 163, in sign
   micalg = "pgp-{}".format(self._get_digest_algo(signature).lower())
 File "/usr/share/goopg/gpgmail.py", line 128, in _get_digest_algo
   raise TypeError("Invalid signature hash_algo {}".format(hash_algo))
TypeError: Invalid signature hash_algo None

The extension shows no relevant errors in the browser background page.

python-gnupg is at version 0.3.7-2 (Debian testing). I installed goopg via PPA, as per instructions on the Readme

**Comment by LeoIannacone** [comment]
It seems the signature.hash_algo is set to None.. this may mean the signature was not valid

https://bitbucket.org/vinay.sajip/python-gnupg/src/2a6d156219a0347777857751d97bff0d27d6bbbb/gnupg.py?at=default&fileviewer=file-view-default#gnupg.py-626:643

Are you sure you can use the key without any problem?

**Comment by LeoIannacone** [comment]
I can confirm this with Ubuntu 15.10

It seems python-gnupg is no longer able to use gpgagent, see this log:

```
2015-09-14 22:49:30,171:DEBUG:gnupg:gpg: gpg-agent is not available in this session
2015-09-14 22:49:30,172:DEBUG:gnupg:gpg: Sorry, no terminal at all requested - can't get input
```

I think something changed recently:
```
$ gpg-agent                                                       
gpg-agent: no gpg-agent running in this session

```

**Comment by LeoIannacone** [comment]
This debian bug seems related to https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=796931

gpg-handler no longer stores the GPG_AGENT_INFO environment variable

**Comment by LeoIannacone** [comment]
For the records:
https://bitbucket.org/vinay.sajip/python-gnupg/issues/32/add-gpg-21-compability
