### ISSUE TITLE
sign messages after changing default key

### ISSUE THREAD

**Issue by Aallam** [LeoIannacone/goopg#22]
I'm new user of the addon, but i have a problem: i can't send any signed email.
![error](https://cloud.githubusercontent.com/assets/1970868/14118668/dba18a30-f5ea-11e5-963a-1afb6bacbfee.png)
this happened after that i deleted my old default key, and defining and new one.

PS: it would be nice if we can simply select the key we want to sign with.

_Resolved: wrong permissions on the file ~/.gpupg/gpg.conf_

**Comment by LeoIannacone** [comment]
Thanks for update your initial message!

Cheers
