### ISSUE TITLE
Python 3 compatibility?

### ISSUE THREAD

**Issue by davesteele** [LeoIannacone/goopg#33]
Do you intend to update the program to Python 3 by 2020?

**Comment by davesteele** [comment]
I have a [start](https://github.com/davesteele/goopg/commits/python3), but I don't expect to get back to it soon.

**Comment by plugwash** [comment]
Debian is in the process of phasing out python 2. The python-fasteners source package has already dropped the python-fasteners binary package which goopg depends on. More packages will likely be dropped going forward and python 2 may (or may not) be dropped completely before the next stable release.

If goopg is going to stay in Debian and return to a future stable release (it was in Stretch but missed buster and is not currently in testing) then it needs to move to python 3 (and the gmail API error issue also needs to be fixed).

(note: i'm just a guy looking at why cruft packages aren't being cleaned up, I don't have any personal interest in this particular package).

**Comment by davesteele** [comment]
I intend to start the process of removing the package from Debian unstable in January, if no progress on the Python 3 migration and API error is made by then.

**Comment by davesteele** [comment]
Removed from Debian Unstable:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=949118
